### ISSUE TITLE
Spack install fails with gcc 7.1.0

### ISSUE THREAD

**Issue by cwsmith** [mfem/mfem#562]
Installing mfem using the gcc 4.8.5 compilers on cooley@ALCF works without any obvious errors.  Building with gcc 7.1.0 on cooley using the following spack command:

`spack install mfem@develop%gcc@7.1.0`

results in the following error:

```
==> Error: ProcessError: Command exited with status 2:
    'make' '-C' 'examples' 'ex1p'

4 errors found in build log:
     214    a - fem/pgridfunc.o
     215    ranlib libmfem.a
     216    ==> 'make' '-C' 'examples' 'ex1p'
     217    make: Entering directory `/gpfs/mira-fs1/projects/ATPESC18_Instructors/FASTMath/cwsmith/spack/var/spack/stage/mfem-develop-gql6oiisnrz27otextph4qsi26k44ssl/mfem/examples'
     218    /soft/libraries/mpi/mvapich2-2.3rc1/gcc/bin/mpicxx  -O3 -I.. -I/projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/hypre-2.14.0-lqtt7fjwta6dywqj67urc33v7jk32bar/include -I/projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/metis-5.1.0-eit3bk6ppy5
            vsldr4tkybjojoq4mwflv/include -I/projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/zlib-1.2.11-p2gbmgo57awstec4wdcb5tge7b6foksr/include ex1p.cpp -o ex1p -L.. -lmfem -Wl,-rpath,/projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/hypre-2.14.0-lqtt
            7fjwta6dywqj67urc33v7jk32bar/lib -Wl,-rpath,/projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/openblas-0.3.0-mfm2f54raovdo2nr7pdqmhejypoamvmr/lib -L/projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/hypre-2.14.0-lqtt7fjwta6dywqj67urc33v7jk32ba
            r/lib -L/projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/openblas-0.3.0-mfm2f54raovdo2nr7pdqmhejypoamvmr/lib -lHYPRE -lopenblas -Wl,-rpath,/projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/metis-5.1.0-eit3bk6ppy5vsldr4tkybjojoq4mwflv/lib -L/
            projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/metis-5.1.0-eit3bk6ppy5vsldr4tkybjojoq4mwflv/lib -lmetis -lrt -Wl,-rpath,/projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/zlib-1.2.11-p2gbmgo57awstec4wdcb5tge7b6foksr/lib -L/projects/ATPESC201
            8/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/zlib-1.2.11-p2gbmgo57awstec4wdcb5tge7b6foksr/lib -lz
     219    /bin/ld: warning: libgfortran.so.4, needed by /projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/openblas-0.3.0-mfm2f54raovdo2nr7pdqmhejypoamvmr/lib/libopenblas.so, not found (try using -rpath or -rpath-link)
  >> 220    /projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/openblas-0.3.0-mfm2f54raovdo2nr7pdqmhejypoamvmr/lib/libopenblas.so: undefined reference to `_gfortran_etime@@GFORTRAN_7'
  >> 221    /projects/ATPESC2018/FASTMath/mfem-pumi/linux-rhel7-x86_64/gcc-7.1.0/openblas-0.3.0-mfm2f54raovdo2nr7pdqmhejypoamvmr/lib/libopenblas.so: undefined reference to `_gfortran_concat_string@@GFORTRAN_7'
  >> 222    collect2: error: ld returned 1 exit status
  >> 223    make: *** [ex1p] Error 1
     224    make: Leaving directory `/gpfs/mira-fs1/projects/ATPESC18_Instructors/FASTMath/cwsmith/spack/var/spack/stage/mfem-develop-gql6oiisnrz27otextph4qsi26k44ssl/mfem/examples'

See build log for details:
  /gpfs/mira-fs1/projects/ATPESC18_Instructors/FASTMath/cwsmith/spack/var/spack/stage/mfem-develop-gql6oiisnrz27otextph4qsi26k44ssl/mfem/spack-build.out
```

compilers.yaml
```
spack config get compilers
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc: /soft/compilers/gcc/7.1.0/bin/gcc
      cxx: /soft/compilers/gcc/7.1.0/bin/g++
      f77: /soft/compilers/gcc/7.1.0/bin/gfortran
      fc: /soft/compilers/gcc/7.1.0/bin/gfortran
    spec: gcc@7.1.0
    target: x86_64
```

packages.yaml

```
packages:
  all:
    compiler: [gcc@7.1.0]
    providers:
      mpi: [ mvapich2 ]
  mvapich2:
    paths:
      mvapich2@2.3: /soft/libraries/mpi/mvapich2-2.3rc1/gcc/
      buildable: False
  cmake:
    paths:
      cmake@3.9.1: /soft/buildtools/cmake/3.9.1/
      buildable: False
```

.soft
```
@default
+mvapich2-2.3rc1
+gcc-7.1.0
+cmake-3.9.1
```
